### ISSUE TITLE
tango starter randomly crashes

### ISSUE THREAD

**Issue by jkotan** [nexdatas/tools#232]
It looks like version of tango server for debian 11 randomly crashes  and causes
```
======================================================================
ERROR: test_addrecorderpath_all (NXSetUp_test.NXSetUpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tango/test/NXSetUp_test.py", line 3457, in test_addrecorderpath_all
    adp.Init()
  File "/usr/lib/python3/dist-packages/tango/device_proxy.py", line 320, in __DeviceProxy__getattr
    raise AttributeError(name)
AttributeError: Init

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tango/test/NXSetUp_test.py", line 3530, in test_addrecorderpath_all
    adp.Init()
  File "/usr/lib/python3/dist-packages/tango/device_proxy.py", line 320, in __DeviceProxy__getattr
    raise AttributeError(name)
AttributeError: Init
```
https://github.com/nexdatas/tools/runs/3716058138?check_suite_focus=true

To fix it we need to install a newer version of tango starter.

**Comment by jkotan** [comment]
I rebuild tango debian11 packages with tango-stater 7.5  (9.3.4+dfsg1-2+deb11u1~fsec) and put them to the HDRI repository so the tests can fetch them.
It should solve the issue.
